[package]
name = "rustc-auto-publish"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
publish = false
edition = "2021"

[dependencies]
cargo_metadata = "0.17.0"
curl = "0.4"
flate2 = "1.0"
semver = { version = "1.0", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4"
tempdir = "0.3"
toml = "0.4"
toml_edit = "0.21.0"
